### ISSUE TITLE
Create website Docker image

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#150]
TODO
-  [ ] Create `website/Dockerfile`
-  [ ] Dockerfile should replicate https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
-  [ ] Test docker container
-  [ ] Create `website/.dockerignore` with the following

```
Dockerfile
.dockerignore
node_modules
npm-debug.log
README.md
.next
.idea
.DS_Store
```

**Comment by harsh18262** [comment]
Hi, As per the template dockerfile( https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile) the app should also generate the standalone package for the app. but currently it is not building it should i add the config for that also and are there any endpoints of the api I can test ?

**Comment by pfwd** [comment]
> Hi, As per the template dockerfile( https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile) the app should also generate the standalone package for the app. but currently it is not building it should i add the config for that also and are there any endpoints of the api I can test ?

Hey @harsh18262 I've merged in some changes that covers this task.  Please run through the steps in the README.md and let me know if you spot any issues with the setup.  If you come across any issues then please raise them as an issue or PR.
