### ISSUE TITLE
Replace jsonServer.rewriter data with routes.json 

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#27]
The following 
```
{
    '/quiz/:slug': '/quiz?slug=:slug'
}
```
in 
```
server.use(jsonServer.rewriter({
    '/quiz/:slug': '/quiz?slug=:slug'
}))
``` 
should be replaced by the `routes.json` file.

An attempt was made to use `path.join(__dirname, 'routes.json'),` as the first argument to `jsonServer.rewriter` but this did not work.

**Comment by metinbaris** [comment]
@pfwd Can work with this one
