### ISSUE TITLE
Add the ability to use .env files

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#28]
Add the ability to use `.env` files to the `api-client`

TODO
- [ ] Install https://www.npmjs.com/package/dotenv
- [ ] Update the `.gitignore` file in the API-Client and ignore the `.env` file
- [ ] Create a `.env.sample` file in the `api-client` root with the following
  - [ ]    `API_VERSION=v1` 
  - [ ]  `API_BASE_PATH=http://localhost:3000/` 
- [ ] Update API-Client [install guide](https://github.com/howToCodeWell/code-quiz/blob/main/api-client/README.md) with a section on how to copy the `.env.sample` to a new `.env` file and make the required changes.

**Comment by metinbaris** [comment]
@pfwd Can help with installing environmental variables
