### ISSUE TITLE
Create a environment variable to store the port

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#29]
By default this is set to port 3000 however this needs to be changeable via an .env file
This cannot happen until #28 is completed

**Comment by pfwd** [comment]
#28 is now complete so this is un-blocked

**Comment by metinbaris** [comment]
@pfwd Do you think this can be closed as we do store the port now in .env as a separate variable?

[.env.sample](https://github.com/howToCodeWell/code-quiz/blob/main/api-client/.env.sample)

**Comment by pfwd** [comment]
> @pfwd Do you think this can be closed as we do store the port now in .env as a separate variable?
> 
> [.env.sample](https://github.com/howToCodeWell/code-quiz/blob/main/api-client/.env.sample)

Yes this is old and should be closed.  Thanks for letting me know
