### ISSUE TITLE
Remove 't' from HTML question 2

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#48]
### Describe the bug

There is a 't' in the 'content' field for HTML question 2.  This shouldn't be there.
The content value should be4
Please remove

### Steps to reproduce

1. View file `api-client/mockData/htmlAnswers.ts`
2. Remove the 't' from line 27

### Expected behavior

The content value should be 4

### OS / Linux distribution

na

**Comment by Mannuel25** [comment]
Hello @pfwd , I'd like to take this up. Kindly assign it to me.

**Comment by pfwd** [comment]
I've assigned it over @Mannuel25 👍
