### ISSUE TITLE
Add JavaScript Quiz fixtures

### ISSUE THREAD

**Issue by pfwd** [howToCodeWell/code-quiz#59]
Create the JavaScript quiz fixtures that have been posted on Instagram/Twitter
Follow the folder/file structure of the HTML Quiz.
[HTML Quiz fixtures:](https://github.com/howToCodeWell/code-quiz/tree/main/api/config/fixtures/quizzes/html-quiz)
[Twitter JavaScript questions](https://twitter.com/search?q=%40howtocodewell%20%23codequiz%20JavaScript&src=typed_query&f=top)

**Comment by metinbaris** [comment]
Hey @pfwd can help with this :)

**Comment by pfwd** [comment]
> Hey @pfwd can help with this :)

Hey @metinbaris thank you for looking into this. I’ve assigned it to you and have let the GH actions process your PR. I will review in the morning.  👍
